### PR TITLE
Add universal ingest file and README file

### PR DESCRIPTION
**Pull request by titipata**

### CODE REVIEW

**Comment by wcatino** [comment]
Thanks, Titipata.  I'm going to commit the code, as soon as I clean up a couple of things.

**Comment by titipata** [comment]
I see, so I think I will close the pull request for now and I will use the one from your commit then.

**Comment by wcatino** [comment]
Did I ever commit any?
I thought I just emailed you the file...

On Tue, Apr 14, 2015 at 10:50 PM, Titipat Achakulvisut <
notifications@github.com> wrote:

> I see, so I think I will close the pull request for now and I will use the
> one from your commit then.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KnowledgeLab/UniversalIngest/pull/2#issuecomment-93178080
> .

## 

William Catino, Ph.D.

Principal Software Engineer

Knowledge Lab | Computation Institute | University of Chicago

wcatino@gmail.com

773.603.9481

**Comment by titipata** [comment]
Oh, no not yet. I think that you won't commit the code so I pull request your code but I will wait for the real cleaned version :)

**Comment by wcatino** [comment]
Hi Titipat,

Ok, sorry.
I'm not holding you up, am I?

Did you try anything with the version that I emailed to you?

Thanks,
Bill

On Tue, Apr 14, 2015 at 11:42 PM, Titipat Achakulvisut <
notifications@github.com> wrote:

> Oh, no not yet. I think that you won't commit the code so I pull request
> your code but I will wait for the real cleaned version :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KnowledgeLab/UniversalIngest/pull/2#issuecomment-93185901
> .

## 

William Catino, Ph.D.

Principal Software Engineer

Knowledge Lab | Computation Institute | University of Chicago

wcatino@gmail.com

773.603.9481

**Comment by titipata** [comment]
No not at all. I didn't have time to try it yet but will do it soon. One good thing if the code is on Git is that I can clone directly to my Amazon (so don't need `scp` for moving file).

**Pull request closed without merging**
